### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stuffa** [txomon/ubus#1]
Is there any documentation on libubus.
I am wanting to use it in my openwrt/lede modules, but I am having trouble finding a place to start
I may have to resort to looking at the code but was hoping that there was an easier path
Is it modeled off another project that is documented?

**Comment by txomon** [comment]
The documentation I created was all about libubox, the module libubus is created over. If you are able to understand all the modules on libubox, you should have an easier way going through ubus.

https://wiki.openwrt.org/doc/techref/libubox

Openwrt/lede has always been about documenting through code. They make a huge enfasis on readable code, but it's true that when many things are going on at the same time, it's easy to lose focus.

I would use all the daemons that have integration with libubus when looking for examples, rpcd, netifd, uhttp2, they all have code that can give you a better picture on the API, capabilities and uses.

Hope this helps!

**Comment by txomon** [comment]
I suppose I can close this now
