### ISSUE TITLE
Error in Linking  (cannot find -lubox)

### ISSUE THREAD

**Issue by arc1986** [txomon/ubus#2]
while linking am getting this error, can you help ?

[ 30%] Linking C shared library libubus.so
/usr/bin/ld: cannot find -lubox

**Comment by txomon** [comment]
You don't have the libubox library in the LD path.

**Comment by txomon** [comment]
I suppose this is solved

**Comment by amaraaon** [comment]
> I suppose this is solved

How to resolve this

**Comment by txomon** [comment]
You need to have the library in the paths you are compiling this with. I'm
afraid this is outside of the scope of the project.
